filter:
    paths: [ "src/*" ]
    excluded_paths: [ "vendor/*", "tests/*" ]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: false

build:
    environment:
        php:
            version: 8.1.2
            ini:
                xdebug.mode: coverage
        mysql: false
        node: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
        before:
            - composer self-update
    tests:
        before:
            -   command: composer test:coverage
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
